services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7000:7000"  # Map port 7000 on the host to port 5000 in the container
    environment:
      - DATABASE_URL=mysql+pymysql://root:6972dk@db:3306/Weatherman
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 6972dk
      MYSQL_DATABASE: Weatherman
    ports:
      - "3306:3306"
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
