version: '3.8'

services:
  # PHP app container
  php-app:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    networks:
      - mynetwork

  # MySQL container 
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: flood_risk_db
    volumes:
      - db-data:/var/lib/mysql
      - ./setup.sql:/docker-entrypoint-initdb.d/weatherman.sql 
    networks:
      - mynetwork

  # Redis container
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  # Flask app container
  flask-app:
    build: ./flask_app
    ports:
      - "5000:5000"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    networks:
      - mynetwork

# Named volume for MySQL data persistence
volumes:
  db-data:

# Define network
networks:
  mynetwork:
    driver: bridge
