services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7000:7000"  # Map port 7000 on the host to port 7000 in the container
    environment:
      - DATABASE_URL=mysql+pymysql://root:6972dk@db:3306/Weatherman
    depends_on:
      db:
        condition: service_healthy  # Wait for the database to be healthy
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 6972dk
      MYSQL_DATABASE: Weatherman
    ports:
      - "3306:3306"
    healthcheck:  # Add a health check for MySQL
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
<<<<<<< HEAD
=======
<<<<<<< HEAD
      
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - app-network
=======
>>>>>>> 42fa128fc2baa9d0cb0a6184d0166457365ed85d
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  mysql_exporter:
    image: prom/mysqld-exporter
    environment:
      DATA_SOURCE_NAME: root:6972dk@(db:3306)/Weatherman
    ports:
      - "9104:9104"
<<<<<<< HEAD
=======
>>>>>>> b36831172537fc728081297df0e16a8108f2a883
>>>>>>> 42fa128fc2baa9d0cb0a6184d0166457365ed85d
