services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7000:7000"  # Map port 7000 on the host to port 7000 in the container
    environment:
      - DATABASE_URL=mysql+pymysql://root:6972dk@db:3306/Weatherman
    depends_on:
      db:
        condition: service_healthy  # Wait for the database to be healthy
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 6972dk
      MYSQL_DATABASE: Weatherman
    ports:
      - "3306:3306"
    healthcheck:  # Add a health check for MySQL
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - app-network
