<<<<<<< HEAD
name: Docker Compose CI/CD
=======
<<<<<<< HEAD
name: Deploy Docker Compose
=======
name: Docker Compose CI/CD
>>>>>>> b36831172537fc728081297df0e16a8108f2a883
>>>>>>> 42fa128fc2baa9d0cb0a6184d0166457365ed85d

on:
  push:
    branches:
<<<<<<< HEAD
=======
<<<<<<< HEAD
      - main  # Deploy on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}  # Add your EC2 instance private key in GitHub Secrets

    - name: Deploy to AWS EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@your-aws-public-ip << 'EOF'
        cd /var/www/html/CS462-Flood-Prediction-and-Monitoring-System  # Replace with your actual path
        git fetch origin
        git reset --hard origin/main
        docker-compose pull  # Update Docker images
        docker-compose up -d --build  # Recreate containers
        EOF
=======
>>>>>>> 42fa128fc2baa9d0cb0a6184d0166457365ed85d
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: <your-acr-name>.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push Docker images
      run: |
        docker-compose -f docker-compose.yml build
        docker-compose -f docker-compose.yml push

    - name: Deploy to Azure
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az container create \
            --resource-group <your-resource-group> \
            --name flood-prediction \
            --image <your-acr-name>.azurecr.io/main-frontend:latest \
            --ports 5002
<<<<<<< HEAD
=======
>>>>>>> b36831172537fc728081297df0e16a8108f2a883
>>>>>>> 42fa128fc2baa9d0cb0a6184d0166457365ed85d
